/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ADP_DemoFPU */

#ifndef _Included_ADP_DemoFPU
#define _Included_ADP_DemoFPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ADP_DemoFPU
 * Method:    REDON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ADP_DemoFPU_REDON
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    REDOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ADP_DemoFPU_REDOFF
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    GREENON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ADP_DemoFPU_GREENON
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    GREENOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ADP_DemoFPU_GREENOFF
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_OPENDEVICE
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1OPENDEVICE
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_CLOSEDEVICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1CLOSEDEVICE
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_ENROLE_EMPLOYEE
 * Signature: (Ljava/lang/String;IJJLADP/FingerPrintEnrollmentHandler;)I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1ENROLE_1EMPLOYEE
  (JNIEnv *, jclass, jstring, jint, jlong, jlong, jobject);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_GET_BADGE_STATUS
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1GET_1BADGE_1STATUS
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_VALIDATE_EMPLOYEE
 * Signature: (Ljava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1VALIDATE_1EMPLOYEE
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_DELETE_TEMPLATE
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1DELETE_1TEMPLATE
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_GET_BADGES
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ADP_DemoFPU_FP_1GET_1BADGES
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_GET_ENROLECOUNT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1GET_1ENROLECOUNT
  (JNIEnv *, jclass);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_GET_TEMPLATE
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ADP_DemoFPU_FP_1GET_1TEMPLATE
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_SET_TEMPLATE
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1SET_1TEMPLATE
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     ADP_DemoFPU
 * Method:    FP_IDENTIFY_EMPLOYEE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ADP_DemoFPU_FP_1IDENTIFY_1EMPLOYEE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
