/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adp_clocks_synergy2416_demo_FPU_Light */

#ifndef _Included_com_adp_clocks_synergy2416_demo_FPU_Light
#define _Included_com_adp_clocks_synergy2416_demo_FPU_Light
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
