/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ADP_DemoFPU_Light */

#ifndef _Included_ADP_DemoFPU_Light
#define _Included_ADP_DemoFPU_Light
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
